name: Publish and Package

on:
  push:
    branches:
      - 'master'
      - 'publish/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.*'

    - name: Publish for Win-x64
      run: dotnet publish -c release -r win-x64 -o ./out/win-x64 --no-self-contained

    - name: Upload artifact for Win-x64 
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-win-x64-${{ github.run_number }}
        path: ./out/win-x64

    - name: Publish Portable
      run: dotnet publish -c release -o ./out/portable --no-self-contained

    - name: Upload artifact for Win-x64 SelfContained
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-portable-${{ github.run_number }}
        path: ./out/portable

    - name: Publish for Win-x64 SelfContained
      run: dotnet publish -c release -r win-x64 -o ./out/win-x64-sc --self-contained

    - name: Upload artifact for Win-x64 SelfContained
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-win-x64-sc-${{ github.run_number }}
        path: ./out/win-x64-sc

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.*'

    - name: Publish for Linux-x64
      run: dotnet publish -c release -r linux-x64 -o ./out/linux-x64 --no-self-contained

    - name: Upload artifact for Linux-x64
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-linux-x64-${{ github.run_number }}
        path: ./out/linux-x64
