name: Publish and Package

on:
  push:
    branches:
      - 'master'
      - 'publish/**'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.*'

    - name: Get commit hash
      id: get_commit_windows  # Different ID for the get_commit step
      run: echo "::set-output name=commit::${GITHUB_SHA::8}"

    - name: Publish for Win-x64
      run: dotnet publish -c release -r win-x64 -o ./out/win-x64 --no-self-contained

    - name: Upload artifact for Win-x64 
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-win-x64-${{ steps.get_commit_windows.outputs.commit }}-${{ github.run_number }}
        path: ./out/win-x64
