name: Publish and Package

on:
  push:
    branches:
      - 'master'
      - 'publish/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.*'

    - name: Publish for Linux-x64
      run: |
        cd FunctionApp44
        dotnet restore
        dotnet publish -c release -r linux-x64 -o ../out/linux-x64 --no-self-contained -p:UseAppHost=false

    - name: Upload artifact for Linux-x64
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts-net7-linux-x64-${{ github.run_number }}
        path: ../out/linux-x64
